// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: schema.tl.custom_auth.proto

package mtproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Auth_AuthMethods struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Methods              []string      `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Auth_AuthMethods) Reset()         { *m = Auth_AuthMethods{} }
func (m *Auth_AuthMethods) String() string { return proto.CompactTextString(m) }
func (*Auth_AuthMethods) ProtoMessage()    {}
func (*Auth_AuthMethods) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fcd888a8178d14b, []int{0}
}
func (m *Auth_AuthMethods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_AuthMethods.Unmarshal(m, b)
}
func (m *Auth_AuthMethods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_AuthMethods.Marshal(b, m, deterministic)
}
func (m *Auth_AuthMethods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_AuthMethods.Merge(m, src)
}
func (m *Auth_AuthMethods) XXX_Size() int {
	return xxx_messageInfo_Auth_AuthMethods.Size(m)
}
func (m *Auth_AuthMethods) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_AuthMethods.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_AuthMethods proto.InternalMessageInfo

func (m *Auth_AuthMethods) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *Auth_AuthMethods) GetMethods() []string {
	if m != nil {
		return m.Methods
	}
	return nil
}

type TLAuthGetAuthMethods struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLAuthGetAuthMethods) Reset()         { *m = TLAuthGetAuthMethods{} }
func (m *TLAuthGetAuthMethods) String() string { return proto.CompactTextString(m) }
func (*TLAuthGetAuthMethods) ProtoMessage()    {}
func (*TLAuthGetAuthMethods) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fcd888a8178d14b, []int{1}
}
func (m *TLAuthGetAuthMethods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLAuthGetAuthMethods.Unmarshal(m, b)
}
func (m *TLAuthGetAuthMethods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLAuthGetAuthMethods.Marshal(b, m, deterministic)
}
func (m *TLAuthGetAuthMethods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLAuthGetAuthMethods.Merge(m, src)
}
func (m *TLAuthGetAuthMethods) XXX_Size() int {
	return xxx_messageInfo_TLAuthGetAuthMethods.Size(m)
}
func (m *TLAuthGetAuthMethods) XXX_DiscardUnknown() {
	xxx_messageInfo_TLAuthGetAuthMethods.DiscardUnknown(m)
}

var xxx_messageInfo_TLAuthGetAuthMethods proto.InternalMessageInfo

func (m *TLAuthGetAuthMethods) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

type TLAuthUsernameRegister struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Username             string        `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string        `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            string        `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLAuthUsernameRegister) Reset()         { *m = TLAuthUsernameRegister{} }
func (m *TLAuthUsernameRegister) String() string { return proto.CompactTextString(m) }
func (*TLAuthUsernameRegister) ProtoMessage()    {}
func (*TLAuthUsernameRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fcd888a8178d14b, []int{2}
}
func (m *TLAuthUsernameRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLAuthUsernameRegister.Unmarshal(m, b)
}
func (m *TLAuthUsernameRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLAuthUsernameRegister.Marshal(b, m, deterministic)
}
func (m *TLAuthUsernameRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLAuthUsernameRegister.Merge(m, src)
}
func (m *TLAuthUsernameRegister) XXX_Size() int {
	return xxx_messageInfo_TLAuthUsernameRegister.Size(m)
}
func (m *TLAuthUsernameRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_TLAuthUsernameRegister.DiscardUnknown(m)
}

var xxx_messageInfo_TLAuthUsernameRegister proto.InternalMessageInfo

func (m *TLAuthUsernameRegister) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLAuthUsernameRegister) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TLAuthUsernameRegister) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TLAuthUsernameRegister) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type TLAuthUsernameSignIn struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Username             string        `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string        `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLAuthUsernameSignIn) Reset()         { *m = TLAuthUsernameSignIn{} }
func (m *TLAuthUsernameSignIn) String() string { return proto.CompactTextString(m) }
func (*TLAuthUsernameSignIn) ProtoMessage()    {}
func (*TLAuthUsernameSignIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fcd888a8178d14b, []int{3}
}
func (m *TLAuthUsernameSignIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLAuthUsernameSignIn.Unmarshal(m, b)
}
func (m *TLAuthUsernameSignIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLAuthUsernameSignIn.Marshal(b, m, deterministic)
}
func (m *TLAuthUsernameSignIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLAuthUsernameSignIn.Merge(m, src)
}
func (m *TLAuthUsernameSignIn) XXX_Size() int {
	return xxx_messageInfo_TLAuthUsernameSignIn.Size(m)
}
func (m *TLAuthUsernameSignIn) XXX_DiscardUnknown() {
	xxx_messageInfo_TLAuthUsernameSignIn.DiscardUnknown(m)
}

var xxx_messageInfo_TLAuthUsernameSignIn proto.InternalMessageInfo

func (m *TLAuthUsernameSignIn) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLAuthUsernameSignIn) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TLAuthUsernameSignIn) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type TLAuthPhonePasswordRegister struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Phone                string        `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string        `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            string        `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLAuthPhonePasswordRegister) Reset()         { *m = TLAuthPhonePasswordRegister{} }
func (m *TLAuthPhonePasswordRegister) String() string { return proto.CompactTextString(m) }
func (*TLAuthPhonePasswordRegister) ProtoMessage()    {}
func (*TLAuthPhonePasswordRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fcd888a8178d14b, []int{4}
}
func (m *TLAuthPhonePasswordRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLAuthPhonePasswordRegister.Unmarshal(m, b)
}
func (m *TLAuthPhonePasswordRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLAuthPhonePasswordRegister.Marshal(b, m, deterministic)
}
func (m *TLAuthPhonePasswordRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLAuthPhonePasswordRegister.Merge(m, src)
}
func (m *TLAuthPhonePasswordRegister) XXX_Size() int {
	return xxx_messageInfo_TLAuthPhonePasswordRegister.Size(m)
}
func (m *TLAuthPhonePasswordRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_TLAuthPhonePasswordRegister.DiscardUnknown(m)
}

var xxx_messageInfo_TLAuthPhonePasswordRegister proto.InternalMessageInfo

func (m *TLAuthPhonePasswordRegister) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLAuthPhonePasswordRegister) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *TLAuthPhonePasswordRegister) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TLAuthPhonePasswordRegister) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type TLAuthPhonePasswordSignIn struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Phone                string        `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string        `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLAuthPhonePasswordSignIn) Reset()         { *m = TLAuthPhonePasswordSignIn{} }
func (m *TLAuthPhonePasswordSignIn) String() string { return proto.CompactTextString(m) }
func (*TLAuthPhonePasswordSignIn) ProtoMessage()    {}
func (*TLAuthPhonePasswordSignIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fcd888a8178d14b, []int{5}
}
func (m *TLAuthPhonePasswordSignIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLAuthPhonePasswordSignIn.Unmarshal(m, b)
}
func (m *TLAuthPhonePasswordSignIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLAuthPhonePasswordSignIn.Marshal(b, m, deterministic)
}
func (m *TLAuthPhonePasswordSignIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLAuthPhonePasswordSignIn.Merge(m, src)
}
func (m *TLAuthPhonePasswordSignIn) XXX_Size() int {
	return xxx_messageInfo_TLAuthPhonePasswordSignIn.Size(m)
}
func (m *TLAuthPhonePasswordSignIn) XXX_DiscardUnknown() {
	xxx_messageInfo_TLAuthPhonePasswordSignIn.DiscardUnknown(m)
}

var xxx_messageInfo_TLAuthPhonePasswordSignIn proto.InternalMessageInfo

func (m *TLAuthPhonePasswordSignIn) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLAuthPhonePasswordSignIn) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *TLAuthPhonePasswordSignIn) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Auth_AuthMethods)(nil), "mtproto.Auth_AuthMethods")
	proto.RegisterType((*TLAuthGetAuthMethods)(nil), "mtproto.TLAuthGetAuthMethods")
	proto.RegisterType((*TLAuthUsernameRegister)(nil), "mtproto.TLAuthUsernameRegister")
	proto.RegisterType((*TLAuthUsernameSignIn)(nil), "mtproto.TLAuthUsernameSignIn")
	proto.RegisterType((*TLAuthPhonePasswordRegister)(nil), "mtproto.TLAuthPhonePasswordRegister")
	proto.RegisterType((*TLAuthPhonePasswordSignIn)(nil), "mtproto.TLAuthPhonePasswordSignIn")
}

func init() { proto.RegisterFile("schema.tl.custom_auth.proto", fileDescriptor_5fcd888a8178d14b) }

var fileDescriptor_5fcd888a8178d14b = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x50, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x25, 0xd4, 0x5a, 0x3b, 0x82, 0xc8, 0x52, 0xcb, 0xda, 0x22, 0xd4, 0xf5, 0xd2, 0xd3, 0x16,
	0xda, 0x8b, 0x57, 0xf5, 0x20, 0x42, 0x95, 0xb2, 0xd6, 0x8b, 0x97, 0x92, 0xa6, 0xe9, 0x66, 0xc1,
	0x6c, 0x4a, 0x32, 0xc1, 0x4f, 0xd0, 0x4f, 0xd1, 0xbf, 0x94, 0x4d, 0x76, 0xb5, 0x07, 0x2f, 0xb2,
	0xc5, 0x4b, 0x92, 0x37, 0x6f, 0xf2, 0xde, 0x9b, 0x81, 0xbe, 0x61, 0x82, 0x4b, 0x1a, 0xe3, 0x4b,
	0xcc, 0xac, 0x41, 0x25, 0x17, 0xd4, 0xa2, 0x88, 0x37, 0x5a, 0xa1, 0x0a, 0x5a, 0x12, 0xdd, 0xa3,
	0x77, 0xb2, 0xd5, 0xa5, 0xd9, 0x64, 0xec, 0xf9, 0x68, 0x0d, 0xc7, 0x57, 0x16, 0xc5, 0xa2, 0x38,
	0xee, 0x39, 0x0a, 0xb5, 0x32, 0xc1, 0x25, 0x1c, 0x32, 0x95, 0x1b, 0xd4, 0x96, 0xa1, 0xd2, 0x21,
	0x19, 0x90, 0xe1, 0xd1, 0xb8, 0x1b, 0x97, 0x4a, 0xf1, 0x7c, 0x7a, 0xf3, 0xc3, 0x26, 0xdb, 0xad,
	0x41, 0x08, 0x2d, 0xe9, 0x45, 0xc2, 0xc6, 0xa0, 0x31, 0x6c, 0x27, 0x15, 0x8c, 0x66, 0xd0, 0x99,
	0x4f, 0x0b, 0x93, 0x5b, 0x8e, 0x3b, 0xf1, 0x8a, 0x3e, 0x09, 0x74, 0xbd, 0xe4, 0x93, 0xe1, 0x3a,
	0xa7, 0x92, 0x27, 0x3c, 0xcd, 0x0c, 0x72, 0x5d, 0x63, 0x80, 0x1e, 0x1c, 0xd8, 0x52, 0x2d, 0x6c,
	0x0c, 0xc8, 0xb0, 0x9d, 0x7c, 0xe3, 0x82, 0xdb, 0x50, 0x63, 0x5e, 0x95, 0x5e, 0x85, 0x7b, 0x9e,
	0xab, 0x70, 0x70, 0x06, 0xb0, 0xce, 0xb4, 0xc1, 0x85, 0xfb, 0xd9, 0x74, 0x6c, 0xdb, 0x55, 0x1e,
	0xa8, 0xe4, 0xd1, 0x3b, 0xa9, 0xc6, 0xaf, 0xb2, 0x3e, 0x66, 0x69, 0x7e, 0x97, 0xff, 0x7f, 0xd2,
	0xe8, 0x83, 0x40, 0xdf, 0x47, 0x99, 0x09, 0x95, 0xf3, 0x59, 0x59, 0xdf, 0xc1, 0xee, 0x3a, 0xd0,
	0xdc, 0x14, 0x92, 0x65, 0x1c, 0x0f, 0xea, 0x6c, 0xed, 0x8d, 0xc0, 0xe9, 0x2f, 0x51, 0x6b, 0xaf,
	0xee, 0xcf, 0x41, 0xaf, 0x2f, 0x9e, 0xcf, 0xd3, 0x0c, 0x85, 0x5d, 0xc6, 0x4c, 0xc9, 0x11, 0x72,
	0x2a, 0x53, 0x4d, 0xe5, 0xc8, 0x39, 0x8d, 0x4a, 0xc7, 0xe5, 0xbe, 0xbb, 0x26, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xf9, 0xae, 0xef, 0x37, 0x90, 0x03, 0x00, 0x00,
}
