# 开发环境配置（bridge 网络）
# 使用方式：docker-compose build && docker-compose up -d
# 需要先启动环境服务：docker-compose -f docker-compose-env.yaml up -d

version: "3"

services:
  teamgram:
    build: .
    restart: always
    ports:
      - "10443:10443"
      - "20450:20450"
      - "20010:20010"
      - "20020:20020"
      - "20640:20640"
      - "20110:20110"
      - "5222:5222"
      - "8801:8801"
      - "20660:20660"
      - "20650:20650"
      - "20030:20030"
      - "20120:20120"
      - "20670:20670"
      - "20420:20420"
      - "6061:6061"
      - "6062:6062"
      - "6063:6063"
    networks:
      - teamgram_net
    mem_limit: 1280m

networks:
  teamgram_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
