// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.0
// source: proto/user_password.proto

package user_password

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserPasswordService_SaveUserPassword_FullMethodName       = "/user_password.UserPasswordService/SaveUserPassword"
	UserPasswordService_GetUserPassword_FullMethodName        = "/user_password.UserPasswordService/GetUserPassword"
	UserPasswordService_GetUserPasswordByPhone_FullMethodName = "/user_password.UserPasswordService/GetUserPasswordByPhone"
)

// UserPasswordServiceClient is the client API for UserPasswordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserPasswordServiceClient interface {
	// 保存用户密码哈希
	SaveUserPassword(ctx context.Context, in *SaveUserPasswordReq, opts ...grpc.CallOption) (*SaveUserPasswordResp, error)
	// 按 user_id 获取密码哈希
	GetUserPassword(ctx context.Context, in *GetUserPasswordReq, opts ...grpc.CallOption) (*GetUserPasswordResp, error)
	// 按手机号获取 user_id + 密码哈希
	GetUserPasswordByPhone(ctx context.Context, in *GetUserPasswordByPhoneReq, opts ...grpc.CallOption) (*GetUserPasswordByPhoneResp, error)
}

type userPasswordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserPasswordServiceClient(cc grpc.ClientConnInterface) UserPasswordServiceClient {
	return &userPasswordServiceClient{cc}
}

func (c *userPasswordServiceClient) SaveUserPassword(ctx context.Context, in *SaveUserPasswordReq, opts ...grpc.CallOption) (*SaveUserPasswordResp, error) {
	out := new(SaveUserPasswordResp)
	err := c.cc.Invoke(ctx, UserPasswordService_SaveUserPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userPasswordServiceClient) GetUserPassword(ctx context.Context, in *GetUserPasswordReq, opts ...grpc.CallOption) (*GetUserPasswordResp, error) {
	out := new(GetUserPasswordResp)
	err := c.cc.Invoke(ctx, UserPasswordService_GetUserPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userPasswordServiceClient) GetUserPasswordByPhone(ctx context.Context, in *GetUserPasswordByPhoneReq, opts ...grpc.CallOption) (*GetUserPasswordByPhoneResp, error) {
	out := new(GetUserPasswordByPhoneResp)
	err := c.cc.Invoke(ctx, UserPasswordService_GetUserPasswordByPhone_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserPasswordServiceServer is the server API for UserPasswordService service.
// All implementations must embed UnimplementedUserPasswordServiceServer
// for forward compatibility
type UserPasswordServiceServer interface {
	// 保存用户密码哈希
	SaveUserPassword(context.Context, *SaveUserPasswordReq) (*SaveUserPasswordResp, error)
	// 按 user_id 获取密码哈希
	GetUserPassword(context.Context, *GetUserPasswordReq) (*GetUserPasswordResp, error)
	// 按手机号获取 user_id + 密码哈希
	GetUserPasswordByPhone(context.Context, *GetUserPasswordByPhoneReq) (*GetUserPasswordByPhoneResp, error)
	mustEmbedUnimplementedUserPasswordServiceServer()
}

// UnimplementedUserPasswordServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserPasswordServiceServer struct {
}

func (UnimplementedUserPasswordServiceServer) SaveUserPassword(context.Context, *SaveUserPasswordReq) (*SaveUserPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveUserPassword not implemented")
}
func (UnimplementedUserPasswordServiceServer) GetUserPassword(context.Context, *GetUserPasswordReq) (*GetUserPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPassword not implemented")
}
func (UnimplementedUserPasswordServiceServer) GetUserPasswordByPhone(context.Context, *GetUserPasswordByPhoneReq) (*GetUserPasswordByPhoneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPasswordByPhone not implemented")
}
func (UnimplementedUserPasswordServiceServer) mustEmbedUnimplementedUserPasswordServiceServer() {}

// UnsafeUserPasswordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserPasswordServiceServer will
// result in compilation errors.
type UnsafeUserPasswordServiceServer interface {
	mustEmbedUnimplementedUserPasswordServiceServer()
}

func RegisterUserPasswordServiceServer(s grpc.ServiceRegistrar, srv UserPasswordServiceServer) {
	s.RegisterService(&UserPasswordService_ServiceDesc, srv)
}

func _UserPasswordService_SaveUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserPasswordServiceServer).SaveUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserPasswordService_SaveUserPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserPasswordServiceServer).SaveUserPassword(ctx, req.(*SaveUserPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserPasswordService_GetUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserPasswordServiceServer).GetUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserPasswordService_GetUserPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserPasswordServiceServer).GetUserPassword(ctx, req.(*GetUserPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserPasswordService_GetUserPasswordByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPasswordByPhoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserPasswordServiceServer).GetUserPasswordByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserPasswordService_GetUserPasswordByPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserPasswordServiceServer).GetUserPasswordByPhone(ctx, req.(*GetUserPasswordByPhoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserPasswordService_ServiceDesc is the grpc.ServiceDesc for UserPasswordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserPasswordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_password.UserPasswordService",
	HandlerType: (*UserPasswordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveUserPassword",
			Handler:    _UserPasswordService_SaveUserPassword_Handler,
		},
		{
			MethodName: "GetUserPassword",
			Handler:    _UserPasswordService_GetUserPassword_Handler,
		},
		{
			MethodName: "GetUserPasswordByPhone",
			Handler:    _UserPasswordService_GetUserPasswordByPhone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user_password.proto",
}
