// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.0
// source: proto/auth_username.proto

package auth_username

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthUsernameService_GetAuthMethods_FullMethodName         = "/auth_username.AuthUsernameService/GetAuthMethods"
	AuthUsernameService_CheckUsernameAvailable_FullMethodName = "/auth_username.AuthUsernameService/CheckUsernameAvailable"
	AuthUsernameService_UsernameRegister_FullMethodName       = "/auth_username.AuthUsernameService/UsernameRegister"
	AuthUsernameService_UsernameSignIn_FullMethodName         = "/auth_username.AuthUsernameService/UsernameSignIn"
	AuthUsernameService_PhonePasswordRegister_FullMethodName  = "/auth_username.AuthUsernameService/PhonePasswordRegister"
	AuthUsernameService_PhonePasswordSignIn_FullMethodName    = "/auth_username.AuthUsernameService/PhonePasswordSignIn"
)

// AuthUsernameServiceClient is the client API for AuthUsernameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthUsernameServiceClient interface {
	// 获取支持的认证方式列表
	GetAuthMethods(ctx context.Context, in *GetAuthMethodsReq, opts ...grpc.CallOption) (*GetAuthMethodsResp, error)
	// 检查用户名是否可用
	CheckUsernameAvailable(ctx context.Context, in *CheckUsernameAvailableReq, opts ...grpc.CallOption) (*CheckUsernameAvailableResp, error)
	// 用户名+密码注册
	UsernameRegister(ctx context.Context, in *UsernameRegisterReq, opts ...grpc.CallOption) (*AuthResp, error)
	// 用户名+密码登录
	UsernameSignIn(ctx context.Context, in *UsernameSignInReq, opts ...grpc.CallOption) (*AuthResp, error)
	// 手机号+密码注册
	PhonePasswordRegister(ctx context.Context, in *PhonePasswordRegisterReq, opts ...grpc.CallOption) (*AuthResp, error)
	// 手机号+密码登录
	PhonePasswordSignIn(ctx context.Context, in *PhonePasswordSignInReq, opts ...grpc.CallOption) (*AuthResp, error)
}

type authUsernameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthUsernameServiceClient(cc grpc.ClientConnInterface) AuthUsernameServiceClient {
	return &authUsernameServiceClient{cc}
}

func (c *authUsernameServiceClient) GetAuthMethods(ctx context.Context, in *GetAuthMethodsReq, opts ...grpc.CallOption) (*GetAuthMethodsResp, error) {
	out := new(GetAuthMethodsResp)
	err := c.cc.Invoke(ctx, AuthUsernameService_GetAuthMethods_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUsernameServiceClient) CheckUsernameAvailable(ctx context.Context, in *CheckUsernameAvailableReq, opts ...grpc.CallOption) (*CheckUsernameAvailableResp, error) {
	out := new(CheckUsernameAvailableResp)
	err := c.cc.Invoke(ctx, AuthUsernameService_CheckUsernameAvailable_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUsernameServiceClient) UsernameRegister(ctx context.Context, in *UsernameRegisterReq, opts ...grpc.CallOption) (*AuthResp, error) {
	out := new(AuthResp)
	err := c.cc.Invoke(ctx, AuthUsernameService_UsernameRegister_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUsernameServiceClient) UsernameSignIn(ctx context.Context, in *UsernameSignInReq, opts ...grpc.CallOption) (*AuthResp, error) {
	out := new(AuthResp)
	err := c.cc.Invoke(ctx, AuthUsernameService_UsernameSignIn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUsernameServiceClient) PhonePasswordRegister(ctx context.Context, in *PhonePasswordRegisterReq, opts ...grpc.CallOption) (*AuthResp, error) {
	out := new(AuthResp)
	err := c.cc.Invoke(ctx, AuthUsernameService_PhonePasswordRegister_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUsernameServiceClient) PhonePasswordSignIn(ctx context.Context, in *PhonePasswordSignInReq, opts ...grpc.CallOption) (*AuthResp, error) {
	out := new(AuthResp)
	err := c.cc.Invoke(ctx, AuthUsernameService_PhonePasswordSignIn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthUsernameServiceServer is the server API for AuthUsernameService service.
// All implementations must embed UnimplementedAuthUsernameServiceServer
// for forward compatibility
type AuthUsernameServiceServer interface {
	// 获取支持的认证方式列表
	GetAuthMethods(context.Context, *GetAuthMethodsReq) (*GetAuthMethodsResp, error)
	// 检查用户名是否可用
	CheckUsernameAvailable(context.Context, *CheckUsernameAvailableReq) (*CheckUsernameAvailableResp, error)
	// 用户名+密码注册
	UsernameRegister(context.Context, *UsernameRegisterReq) (*AuthResp, error)
	// 用户名+密码登录
	UsernameSignIn(context.Context, *UsernameSignInReq) (*AuthResp, error)
	// 手机号+密码注册
	PhonePasswordRegister(context.Context, *PhonePasswordRegisterReq) (*AuthResp, error)
	// 手机号+密码登录
	PhonePasswordSignIn(context.Context, *PhonePasswordSignInReq) (*AuthResp, error)
	mustEmbedUnimplementedAuthUsernameServiceServer()
}

// UnimplementedAuthUsernameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthUsernameServiceServer struct {
}

func (UnimplementedAuthUsernameServiceServer) GetAuthMethods(context.Context, *GetAuthMethodsReq) (*GetAuthMethodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthMethods not implemented")
}
func (UnimplementedAuthUsernameServiceServer) CheckUsernameAvailable(context.Context, *CheckUsernameAvailableReq) (*CheckUsernameAvailableResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUsernameAvailable not implemented")
}
func (UnimplementedAuthUsernameServiceServer) UsernameRegister(context.Context, *UsernameRegisterReq) (*AuthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsernameRegister not implemented")
}
func (UnimplementedAuthUsernameServiceServer) UsernameSignIn(context.Context, *UsernameSignInReq) (*AuthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsernameSignIn not implemented")
}
func (UnimplementedAuthUsernameServiceServer) PhonePasswordRegister(context.Context, *PhonePasswordRegisterReq) (*AuthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PhonePasswordRegister not implemented")
}
func (UnimplementedAuthUsernameServiceServer) PhonePasswordSignIn(context.Context, *PhonePasswordSignInReq) (*AuthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PhonePasswordSignIn not implemented")
}
func (UnimplementedAuthUsernameServiceServer) mustEmbedUnimplementedAuthUsernameServiceServer() {}

// UnsafeAuthUsernameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthUsernameServiceServer will
// result in compilation errors.
type UnsafeAuthUsernameServiceServer interface {
	mustEmbedUnimplementedAuthUsernameServiceServer()
}

func RegisterAuthUsernameServiceServer(s grpc.ServiceRegistrar, srv AuthUsernameServiceServer) {
	s.RegisterService(&AuthUsernameService_ServiceDesc, srv)
}

func _AuthUsernameService_GetAuthMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthMethodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUsernameServiceServer).GetAuthMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUsernameService_GetAuthMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUsernameServiceServer).GetAuthMethods(ctx, req.(*GetAuthMethodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUsernameService_CheckUsernameAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUsernameAvailableReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUsernameServiceServer).CheckUsernameAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUsernameService_CheckUsernameAvailable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUsernameServiceServer).CheckUsernameAvailable(ctx, req.(*CheckUsernameAvailableReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUsernameService_UsernameRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsernameRegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUsernameServiceServer).UsernameRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUsernameService_UsernameRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUsernameServiceServer).UsernameRegister(ctx, req.(*UsernameRegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUsernameService_UsernameSignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsernameSignInReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUsernameServiceServer).UsernameSignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUsernameService_UsernameSignIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUsernameServiceServer).UsernameSignIn(ctx, req.(*UsernameSignInReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUsernameService_PhonePasswordRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhonePasswordRegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUsernameServiceServer).PhonePasswordRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUsernameService_PhonePasswordRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUsernameServiceServer).PhonePasswordRegister(ctx, req.(*PhonePasswordRegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUsernameService_PhonePasswordSignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhonePasswordSignInReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUsernameServiceServer).PhonePasswordSignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUsernameService_PhonePasswordSignIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUsernameServiceServer).PhonePasswordSignIn(ctx, req.(*PhonePasswordSignInReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthUsernameService_ServiceDesc is the grpc.ServiceDesc for AuthUsernameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthUsernameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_username.AuthUsernameService",
	HandlerType: (*AuthUsernameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthMethods",
			Handler:    _AuthUsernameService_GetAuthMethods_Handler,
		},
		{
			MethodName: "CheckUsernameAvailable",
			Handler:    _AuthUsernameService_CheckUsernameAvailable_Handler,
		},
		{
			MethodName: "UsernameRegister",
			Handler:    _AuthUsernameService_UsernameRegister_Handler,
		},
		{
			MethodName: "UsernameSignIn",
			Handler:    _AuthUsernameService_UsernameSignIn_Handler,
		},
		{
			MethodName: "PhonePasswordRegister",
			Handler:    _AuthUsernameService_PhonePasswordRegister_Handler,
		},
		{
			MethodName: "PhonePasswordSignIn",
			Handler:    _AuthUsernameService_PhonePasswordSignIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth_username.proto",
}
